### ISSUE TITLE
Could not resolve all artifacts for configuration ':classpath'

### ISSUE THREAD

**Issue by MeetShah29** [rvi/ONVIFCameraAndroid#22]
Could not find com.jfrog.bintray.gradle:gradle-bintray-plugin:1.8.5.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.8.5/gradle-bintray-plugin-1.8.5.pom
       - []([]([]([](https://repo.maven.apache.org/maven2/com/jfrog/bintray/gradle/gradle-bintray-plugin/1.8.5/gradle-bintray-plugin-1.8.5.pom[](url)))))

**Comment by rvi** [comment]
Hey @MeetShah29, sorry for the late reply. Have you tried looking on [this repo](https://github.com/bintray/gradle-bintray-plugin)?
