### ISSUE TITLE
Connecting by Serial Number

### ISSUE THREAD

**Issue by annanoell** [rvi/ONVIFCameraAndroid#6]
Hi,

Is it possible to access to ONVIF camera via Serial Number instead of ip using this library? We cannot open ports. 

Thanks!!!

**Comment by rvi** [comment]
Hi,

I think what you're looking for is _Discovery_. There is a small chapter on this on [ONVIF docs](https://www.onvif.org/wp-content/uploads/2018/09/ONVIF_Profile_T_Specification_v1-0.pdf).

**Comment by rvi** [comment]
Closing this one, since I don't have any updates.
