### ISSUE TITLE
405 - Method Not Allowed

### ISSUE THREAD

**Issue by faith-hb** [rvi/ONVIFCameraAndroid#7]
405 - Method Not Allowed，The callback function reports an error when you click to connect the device

**Comment by rvi** [comment]
Sorry for the late reply, can you provide a backtrace?

**Comment by J1EXA** [comment]
The following classes could not be found:
- android.support.constraint.ConstraintLayout (    Add constraint-layout library dependency to the project, Fix Build Path, Edit XML, Create Class)
 Tip: Try to build the project.   Tip: Try to refresh the layout.
