### ISSUE TITLE
Failed to connect to /192.168.48.180:8554

### ISSUE THREAD

**Issue by faith-hb** [rvi/ONVIFCameraAndroid#8]
Has been unable to connect, I hope the landlord answer questions

**Comment by Tejas1295** [comment]
Search your router IP address on the internet by googling whats my ip? Use that IP along with the port you mentioned i.e. 8554 and let me know if it works.

**Comment by rvi** [comment]
Can't help you with more context ;)

**Comment by rvi** [comment]
Closing this one, since I don't have any updates.
