### ISSUE TITLE
ErrorCode 500, Internal Server Error on getProfiles()

### ISSUE THREAD

**Issue by HevilPrajapati** [rvi/ONVIFCameraAndroid#9]
Hello, i am new to this technology. I am getting Internal server error, Error Code is 500. Please help me to resolve this issue. I've gone through documentation it's easy to understand. I am not able to get media profiles and rtsp url also. Please help. Here are the log details.
### getServices() ###
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope" ><soap:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:Username>admin</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">cMY4zICXTSgiZIMCaLrScottS/A=</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">MjE2ZDM5MzAtYjM5My00MzA0LWFhYzYtNzU2NDBmZGFhNmI5
    </wsse:Nonce><wsu:Created>2019-10-16T06:13:000Z</wsu:Created></wsse:UsernameToken></wsse:Security></soap:Header><soap:Body><GetServices xmlns="http://www.onvif.org/ver10/device/wsdl"><IncludeCapability>false</IncludeCapability></GetServices></soap:Body></soap:Envelope>
true
Request GetServices performed.

### getDeviceInformation() ###
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope" ><soap:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:Username>admin</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">EhkGLRFAOzgjd/UihGLedGjYvJI=</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">ODBlYzBkYWItNGRlYi00ODI5LWE1ZDAtODNhMTAzMDcyZjZj
    </wsse:Nonce><wsu:Created>2019-10-16T06:13:000Z</wsu:Created></wsse:UsernameToken></wsse:Security></soap:Header><soap:Body><GetDeviceInformation xmlns="http://www.onvif.org/ver10/device/wsdl"></GetDeviceInformation></soap:Body></soap:Envelope>	
true
Request GetDeviceInformation performed.
Device information:
    Manufacturer: HIKVISION
    Model: DS-2CD122P-I3
    FirmwareVersion: V5.4.50 build 180602
    SerialNumber: DS-2CD122P-I320190604AAWR234641390

### getProfiles() ###
<?xml version="1.0" encoding="utf-8"?><soap:Envelope xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://www.w3.org/2003/05/soap-envelope" ><soap:Header><wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd"><wsse:UsernameToken xmlns:wsu="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd"><wsse:Username>admin</wsse:Username><wsse:Password Type="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest">THOWbf+eUm4MBI8xVKMi+taceic=</wsse:Password><wsse:Nonce EncodingType="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary">MTNjOGQ1OWItMTZhNC00MDdjLWEzMTgtYTM1MWZjZGQ1NTky
    </wsse:Nonce><wsu:Created>2019-10-16T06:13:000Z</wsu:Created></wsse:UsernameToken></wsse:Security></soap:Header><soap:Body><GetProfiles xmlns="http://www.onvif.org/ver10/media/wsdl"/></soap:Body></soap:Envelope>
 Response{protocol=http/1.1, code=500, message=Internal Server Error, url=http://ipaddress:port/onvif/device_service}
false
Request GetProfiles performed.

**Comment by rvi** [comment]
That's weird, I believe it's something wrong with your camera. Can you check if it's up to date and if it conforms with the [profile T](https://www.onvif.org/profiles/profile-t/)?

**Comment by rvi** [comment]
Closing this one, since I don't have any updates.

**Comment by rvi** [comment]
Closing this one, since I don't have any updates.

**Comment by navidcity** [comment]
@HevilPrajapati @rvi 
I have the same issue with the same Camera as @HevilPrajapati had used.
I can communicate with other brands. It seems that something is wrong with HIKVISION cameras.
